esphome:
  name: tfminiplus
  platform: ESP32
  board: esp32dev 

  includes:
    - TFMiniPlus.h
  
  libraries:
    - "TFMPlus"
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "OTA Password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TFMiniPlus"
    password: "password"

captive_portal:

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyDistanceSensor();
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
  - name: "Distance Sensor"
    unit_of_measurement: "cm"
    accuracy_decimals: 0
